<?php

	namespace App\Enums;

	enum PlayerActivityEnums: string
	{
		case USER_REGISTER = "USER_REGISTER";
		case USER_LOGIN = "USER_LOGIN";
		case USER_LOGOUT = "USER_LOGOUT";
		case REGISTRATION = "REGISTRATION";
		case PASSWORD_CHANGE = "PASSWORD_CHANGE";
		case ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
		case REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
		case UPDATE_PHONE = "UPDATE_PHONE";
		case UPDATE_PLAYER_PROFILE = "UPDATE_PLAYER_PROFILE";
		case UPDATE_PLAYER_SETTINGS = "UPDATE_PLAYER_SETTINGS";
		case USER_SEARCH = "USER_SEARCH";
		case PLACE_BET = "PLACE_BET";
		case USER_DEPOSIT = "USER_DEPOSIT";
		case USER_WITHDRAW = "USER_WITHDRAW";
		case USER_TIPS = "USER_TIPS";
		case UPDATE_PLAYER_PREFERENCES = "UPDATE_PLAYER_PREFERENCES";
		case CREATE_PLAY_SESSION = "CREATE_PLAY_SESSION";
		case DESTROY_PLAY_SESSION = "DESTROY_PLAY_SESSION";
		case UPDATE_PLAY_SESSION = "UPDATE_PLAY_SESSION";
		case CREATE_PLAY_SESSION_ERROR = "CREATE_PLAY_SESSION_ERROR";
		case RECENT_GAME = "RECENT_GAME";
	}