<?php
	return [
		"allowAutoplay" => 1,
		"minSpinSeconds" => 3,
		"allowSlamStop" => 0,
		"showStatsRequired" => 0,
		"allowFastSpinMode" => 0,
		"errorDisplayLevel" => "INGAME",
		"lobbyURL" => "",
		"lobbyURLMobile" => "",
		"depositURL" => "",
		"depositURLmobile" => "",
		"displayStatusBar" => 1,
		"displayLoader" => 1,
		"loaderStyles" => "",
		"loaderLogo" => "",
		//status bar settings
		"clockLabel" => "",
		"clockDisplay" => 1,
		"clockBarPosition" => "top",
		"clockPosition" => 0,
		"clockMode" => "local",
		"gameNameLabel" => "",
		"gameNameDisplay" => 1,
		"gameNameBarPosition" => "top",
		"gameNamePosition" => 0,
		"balanceLabel" => "Balance",
		"balanceDisplay" => 1,
		"balanceBarPosition" => "bottom",
		"balancePosition" => 0,
		"betLabel" => "Ticket Cost",
		"betDisplay" => 1,
		"betBarPosition" => "bottom",
		"betPosition" => 0,
		"winLabel" => "Wins",
		"winDisplay" => 1,
		"winBarPosition" => "bottom",
		"winPosition" => 0,
		"demoLabel" => "Demo MODE",
		"responsibleGaming" => "",
		"statusBarBackgroundColor" => "",
	];